model:
  path: ./weights/facepoints_resnet_nme_0_0469.pth
  filename: model_state_dict_v1.pth
  input_size: 224
  model_type: resnet

data:
  path: ./data/
  metadata_path: ./data/gt.csv
  chunk_size: 256

training:
  device: mps
  epochs: 200
  lr: 0.001
  weight_decay: 0.00001
  use_scheduler: true
  early_stopping_delta: 0.000001
  use_amp: true
  filename: latest
  save_dir: ./weights/
  save_weights_only: false
  patience: 30

dataset:
  image_size: 224
  flip_prob: 0.5
  normalize_targets: true
  return_meta: false

dataloader:
  batch_size: 16
  pin_memory: false

detector:
  device: mps

inference:
  save: false
  save_dir: ./output/
  metric: null
  gt_path: null
  vis: null
  save_vis: false


detect:
  batch_size: 16
  use_amp: false
  pin_memory: true