model:
  input_size: 224

training:
  epochs: 20
  lr: 0.001
  weight_decay: 0.00001
  use_scheduler: true
  early_stopping_delta: 0.000001
  use_amp: true
  normalize_targets: false
  filename: latest
  save_weights_only: false
  patience: 20

dataset:
  image_size: 224
  flip_prob: 0.5
  return_meta: false

dataloader:
  batch_size: 16
  pin_memory: false